### ISSUE TITLE
converting UTC on web bug.

### ISSUE THREAD

**Issue by asepkampak** [ytti/oxidized-web#91]
oxidized-web-0.6.0
oxidized-script-0.1.1
oxidized-0.9.0 

converting time UTC in web UI only work on first page, the next page still showing UTC.

![page 1](https://cloud.githubusercontent.com/assets/16773415/12502252/111f5a1a-c0f9-11e5-8e13-8c75e516df8b.png)
![page 2](https://cloud.githubusercontent.com/assets/16773415/12502256/17011298-c0f9-11e5-8f3f-21f27e6dccdf.png)

**Comment by supertylerc** [comment]
I don't have enough nodes in my lab to test this, but I think the fix would be easy. Probably just an on click event listener that will convert the time. I'll look into it this weekend and change the number of elements for pagination to a really low number so I can test it properly.

**Comment by asepkampak** [comment]
im sorry, where i can find event listener?

**Comment by supertylerc** [comment]
@asepkampak an event listener/handler in JavaScript.  I've pushed a change to my fork, but I left my laptop at work Friday, so I can't test anything until tomorrow Night.

I'll try to test tomorrow and submit a PR with the appropriate changes.

**Comment by supertylerc** [comment]
Sorry for the delay caused by me leaving the lab laptop at work, but hopefully it's not too long.

**Comment by asepkampak** [comment]
after i adding script, the page still showing UTC.
![utc](https://cloud.githubusercontent.com/assets/16773415/12570819/b4c901ea-c40d-11e5-95e8-92f0b851736d.png)

sorry @supertylerc always make you busy. :)

**Comment by supertylerc** [comment]
Hi, @asepkampak!  Please don't be sorry.  This software is better because of bug reports and help!

Now that I have my laptop which has my lab setup on it, I've been able to test and have found a solution that will work!  I've just submitted #94 to resolve this issue.  I tested this by setting the number of records to display to one in a two node lab and clicking the `Next`, `Previous`, `1`, and `2` buttons with page refreshes in between.  For all four events, I found the correct time was displayed.

If you want to try #94 and let me know if it works, that would be great (but I'm pretty sure it works).

**Comment by asepkampak** [comment]
thanks @supertylerc its work perfectly.
every page now showing convert time thanks.
